# Site settings
baseurl = "https://example.org/"
languageCode = "de"
title = "Ruprecht [Kreativ Lackier-Atelier]"
# theme = "agency"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Daniel Ruprecht"
  description = "Corporate Website von Ruprecht Kreativ Lackier-Atelier. (C) 2018"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Die Seite konnte nicht gefunden werden."
    text = "Klicken Sie hier weiter: [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Ruprecht"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Atelier"
    portfolio = "Portfolio"
    about = "Geschichte"
    team = "Über uns"
    contact = "Kontakt"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Willkommen bei Ruprecht!"
    subtitle = "Lackieren ist eine hohe Kunst, die wir jeden Tag aufs neue ausüben"
    buttonText = "Erfahre mehr"


  # Services section
  [params.services]
    enable = true
    title = "Dienstleistung"
    subtitle = "Das machen wir alles:"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-paint-brush"
      title = "Lackieren"
      description = "Das Kreativ-Atelier lackiert so ziemlich alles wie Holz, Plastik oder Metall. "
      #url = "#"

    [[params.services.row.list]]
      icon = "fa-magic"
      title = "Umlackieren"
      description = "Im Nu sind wir fähig einem Stück mit einer anderen Beschichtung neues Leben einzuhauchen."
      #url = "#"

    [[params.services.row.list]]
      icon = "fa-home"
      title = "Kunst im Bau"
      description = "Nur allzu gerne lackieren wir Möbel und Baustücke."
      #url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = "Eine kleine Auswahl von Aufträgen, die mir richtig Spass gemacht haben."

    [params.portfolio.modal]
      client = "Kunde"
      date = "Datum"
      category = "Kategorie"
      buttonText = "Schliessen"


    # About section
  [params.about]
    enable = true
    title = "Unsere Erfolgsgeschichte"
    subtitle = "Wie es zum Kreativ-Atelier kam."
    endpoint = "Und das ist<br>erst der<br>Anfang!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "2009-2011"
      title = "Am Anfang war ich alleine"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "2.jpg"
      date = "März 2011"
      title = "Dann kam die Ziegelei"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "3.jpg"
      date = "Dezember 2012"
      title = "Und dann die Kunden"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "4.jpg"
      date = "Februar 2018"
      title = "Heute"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Unser Superteam"
    subtitle = "Meine liebsten"
    description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Daniel Ruprecht"
      position = "Der Chef"

    [[params.team.members]]
      img = "2.png"
      name = "Marc Vosseberg"
      position = "Lackierer"

    [[params.team.members]]
      img = "2.png"
      name = "David Buser"
      position = "Lackierer"

    [[params.team.members]]
      img = "2.png"
      name = "Iwen Meister"
      position = "Lernender"

    [[params.team.members]]
      img = "miro.png"
      name = "Miro"
      position = "Werkstattshüter"

  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "stoecklin.jpg"
        link = "http://www.stoecklin-kuechen.ch/de/"

      [[params.clients]]
        logo = "domino.jpg"
        link = "http://www.dominoag.ch"

      [[params.clients]]
        logo = "tschudin.jpg"
        link = "https://www.tschudinag.ch/news.html"

      [[params.clients]]
        logo = "grafe.jpg"
        link = "http://grafe.ch/de/"

      [[params.clients]]
        logo = "frey.jpg"
        link = "http://holz-textilien.ch"

      [[params.clients]]
        logo = "wiwag.jpg"
        link = ""

  # Contact section
  [params.contact]
    enable = true
    title = "Kontaktiere mich"
    subtitle  = " "
    #buttonText = "Absenden"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    #email = "ruprecht@lackier-atelier.ch"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    #[params.contact.form.name]
    #  text = "Dein Name *"
    #  warning = "Gebe hier bitte Deinen Namen an."

    #[params.contact.form.email]
    #  text = "Dein E-Mail *"
    #  warning = "Gebe hier bitte Deine E-Mail an."

    #[params.contact.form.phone]
    #  text = "Deine Telefonnummer*"
    #  warning = "Gebe hier bitte Deine Telefonnummer an."

    #[params.contact.form.message]
    #  text = "Deine Nachricht *"
    #  warning = "Schreibe hier Deine Nachricht an mich."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "(c) Copyright Ruprecht"

    [[params.footer.quicklinks]]
      text = "SVILM"
      link = "http://www.svilm.ch/de/"
